# Generated by Django 3.2.16 on 2023-04-28 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0003_auto_20230428_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['date_added']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_added']},
        ),
        migrations.AlterModelOptions(
            name='forumpost',
            options={'ordering': ['date_added']},
        ),
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['date_added']},
        ),
    ]
