# Generated by Django 3.2.16 on 2023-05-07 19:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0007_consultation_consultationcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='date_added',
        ),
        migrations.AddField(
            model_name='consultation',
            name='complaint',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='consultation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='notes',
        ),
        migrations.AddField(
            model_name='consultation',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='life.notes'),
        ),
    ]
