# Generated by Django 3.2.16 on 2023-05-07 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0008_auto_20230507_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_comments', to='life.consultationcomment'),
        ),
    ]
