# Generated by Django 3.2.15 on 2023-06-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0011_auto_20230607_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='notes',
        ),
        migrations.AddField(
            model_name='consultation',
            name='notes',
            field=models.ManyToManyField(blank=True, to='life.Notes'),
        ),
    ]
