# Generated by Django 3.2.15 on 2023-06-07 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0012_auto_20230607_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctor_notes',
        ),
        migrations.AddField(
            model_name='notes',
            name='consultation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='life.consultation'),
        ),
    ]
