# Generated by Django 3.2.15 on 2023-06-12 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0013_auto_20230607_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forumcomments', to='life.comment'),
        ),
    ]
