# Generated by Django 3.2.15 on 2023-06-12 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0014_forumpost_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumpost',
            old_name='comment',
            new_name='comments',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='life.forumpost'),
        ),
    ]
