# Generated by Django 3.2.15 on 2023-06-12 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0015_auto_20230612_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forumpost', to='life.comment'),
        ),
    ]
