# Generated by Django 3.2.15 on 2023-06-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0016_alter_forumpost_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='comments',
        ),
        migrations.AddField(
            model_name='forumpost',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='forumpost', to='life.Comment'),
        ),
    ]
