# Generated by Django 3.2.15 on 2023-06-12 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0017_auto_20230612_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forumpost', to='life.forumpost'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comment', to='life.Comment'),
        ),
    ]
